# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certyfikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.CharField(max_length=20)),
                ('szczegoly', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Certyfikaty_Dla_Produktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_certyfikatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Certyfikat')),
            ],
        ),
        migrations.CreateModel(
            name='Dodatek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dziedzina_Odziezy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kolor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Opis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer', models.IntegerField()),
                ('opis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('waga', models.IntegerField()),
                ('sztuk', models.IntegerField()),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Firma')),
            ],
        ),
        migrations.CreateModel(
            name='Rodzaj_Odziezy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('id_dziedzina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Dziedzina_Odziezy')),
            ],
        ),
        migrations.CreateModel(
            name='Typ_Odziezy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zagrozenia_Dla_Produktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Zagrozenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zakladka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_url', models.CharField(max_length=50)),
                ('nazwa', models.CharField(max_length=50)),
                ('zawartosc_html', models.TextField()),
                ('zawartosc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zawod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zawody_Dla_Produktu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produktu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Produkt')),
                ('id_zawodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Zawod')),
            ],
        ),
        migrations.AddField(
            model_name='zagrozenia_dla_produktu',
            name='id_zagrozenia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Zagrozenie'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='id_rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Rodzaj_Odziezy'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='kolor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Kolor'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='opis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Opis'),
        ),
        migrations.AddField(
            model_name='dziedzina_odziezy',
            name='id_typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Typ_Odziezy'),
        ),
        migrations.AddField(
            model_name='dodatek',
            name='id_produktu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Produkt'),
        ),
        migrations.AddField(
            model_name='certyfikaty_dla_produktu',
            name='id_produktu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asbhp.Produkt'),
        ),
        migrations.AlterUniqueTogether(
            name='zawody_dla_produktu',
            unique_together=set([('id_produktu', 'id_zawodu')]),
        ),
        migrations.AlterUniqueTogether(
            name='zagrozenia_dla_produktu',
            unique_together=set([('id_produktu', 'id_zagrozenia')]),
        ),
        migrations.AlterUniqueTogether(
            name='certyfikaty_dla_produktu',
            unique_together=set([('id_produktu', 'id_certyfikatu')]),
        ),
    ]
